#!/usr/bin/env python3
"""Execute COMPASS run files for the actual stack preprocessing/coregistration.

Technical summary:
    Loads run files prepared by COMPASS, executes each shell runfile, appends
    output to per-run logs, and tracks status in `run_state.json` for resume.

Why:
    Run the heavy preprocessing/coreg steps safely with restart-friendly state.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from tqdm import tqdm

from stack_common import read_toml, resolve_path


def load_state(path: Path) -> dict:
    """Load run execution state from JSON.

    Args:
        path: Path to run state file.

    Returns:
        State dictionary. Returns an empty default state if file is missing.
    """
    if not path.exists():
        return {"runs": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def save_state(path: Path, state: dict) -> None:
    """Persist run execution state to JSON.

    Args:
        path: Path to state file.
        state: State dictionary to write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    state["updated_utc"] = datetime.now(timezone.utc).isoformat()
    path.write_text(json.dumps(state, indent=2), encoding="utf-8")


def run_one(runfile: Path, logfile: Path) -> int:
    """Execute one COMPASS run file and append output to a log.

    Why:
        This step performs the real COMPASS processing work for one run file.

    Args:
        runfile: Shell script generated by COMPASS.
        logfile: Destination log file path.

    Returns:
        Process return code.
    """
    logfile.parent.mkdir(parents=True, exist_ok=True)
    with logfile.open("a", encoding="utf-8") as log:
        start = datetime.now(timezone.utc).isoformat()
        log.write(f"\n[{start}] START {runfile}\n")
        proc = subprocess.run(
            ["bash", str(runfile)],
            stdout=log,
            stderr=subprocess.STDOUT,
            check=False,
        )
        end = datetime.now(timezone.utc).isoformat()
        log.write(f"[{end}] END rc={proc.returncode}\n")
        return proc.returncode


def main() -> int:
    """Parse CLI args and execute pending COMPASS run files.

    Why:
        Run the prepared coregistration/preprocessing tasks in a resumable way.

    Technical details:
        - Resolves work/log directories from config with CLI overrides.
        - Skips completed runfiles unless `--no-resume` is used.
        - Writes per-run status, timestamps, return codes, and log paths.
        - Supports capped trial runs and optional continue-on-error mode.

    Returns:
        Exit code (0 for success).
    """
    parser = argparse.ArgumentParser(
        description="Execute COMPASS run files generated by prepare_compass_stack.py."
    )
    parser.add_argument(
        "--config",
        default="miami/insar/us_isleofnormandy_s1_asc_t48/config/stack.toml",
        help="Path to stack TOML config.",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root directory (default: current directory).",
    )
    parser.add_argument(
        "--work-dir",
        default="",
        help="COMPASS work dir override (defaults to processing.compass.work_dir).",
    )
    parser.add_argument(
        "--logs-dir",
        default="",
        help="Logs directory override (default: stack logs/compass).",
    )
    parser.add_argument(
        "--max-runfiles",
        type=int,
        default=0,
        help="Optional cap on number of pending run files (0 = all).",
    )
    parser.add_argument(
        "--no-resume",
        action="store_true",
        help="Re-run run files even if marked completed in state file.",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue processing remaining run files after a failure.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only show what would be run.",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    config_path = resolve_path(repo_root, args.config)
    cfg = read_toml(config_path)
    compass_cfg = cfg.get("processing", {}).get("compass", {})

    work_dir_value = args.work_dir or compass_cfg.get(
        "work_dir", "miami/insar/us_isleofnormandy_s1_asc_t48/stack/compass"
    )
    work_dir = resolve_path(repo_root, work_dir_value)
    run_dir = work_dir / "run_files"
    if not run_dir.exists():
        print(f"Missing run_files directory: {run_dir}", file=sys.stderr)
        print("Run prepare_compass_stack.py first.", file=sys.stderr)
        return 2

    logs_default = "miami/insar/us_isleofnormandy_s1_asc_t48/logs/compass"
    logs_dir = resolve_path(repo_root, args.logs_dir or compass_cfg.get("logs_dir", logs_default))
    state_path = work_dir / "run_state.json"

    runfiles = sorted(run_dir.glob("run_*.sh"))
    if not runfiles:
        print(f"No run files found under {run_dir}", file=sys.stderr)
        return 2

    state = load_state(state_path)
    state_runs: dict = state.setdefault("runs", {})
    resume = not args.no_resume
    pending: list[Path] = []
    skipped_completed = 0
    for rf in runfiles:
        prev = state_runs.get(rf.name, {})
        if resume and prev.get("status") == "completed":
            skipped_completed += 1
            continue
        pending.append(rf)

    if args.max_runfiles > 0:
        pending = pending[: args.max_runfiles]

    print(f"Config: {config_path}")
    print(f"Work dir: {work_dir}")
    print(f"Run files total: {len(runfiles)}")
    print(f"Resume mode: {resume}")
    print(f"Already completed (skipped): {skipped_completed}")
    print(f"Pending to run now: {len(pending)}")
    print(f"Logs dir: {logs_dir}")
    print(f"State file: {state_path}")

    if args.dry_run:
        return 0

    if not pending:
        print("Nothing to run.")
        return 0

    failures = 0
    with tqdm(total=len(pending), desc="COMPASS runfiles", unit="run", dynamic_ncols=True) as bar:
        for rf in pending:
            tqdm.write(f"Running: {rf.name}")
            started = datetime.now(timezone.utc).isoformat()
            log_path = logs_dir / f"{rf.stem}.log"
            rc = run_one(rf, log_path)
            finished = datetime.now(timezone.utc).isoformat()

            state_runs[rf.name] = {
                "status": "completed" if rc == 0 else "failed",
                "returncode": rc,
                "log_file": str(log_path),
                "started_utc": started,
                "finished_utc": finished,
            }
            save_state(state_path, state)
            bar.update(1)

            if rc != 0:
                failures += 1
                tqdm.write(f"FAILED: {rf.name} (rc={rc}) -> {log_path}")
                if not args.continue_on_error:
                    break

    print(f"Failures in this run: {failures}")
    print(f"State updated: {state_path}")
    if failures > 0:
        return 4
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
