#!/usr/bin/env python3
"""Execute COMPASS run files for the actual stack preprocessing/coregistration.

Technical summary:
    Loads run files prepared by COMPASS, executes each shell runfile, appends
    output to per-run logs, and tracks status in `run_state.json` for resume.

Why:
    Run the heavy preprocessing/coreg steps safely with restart-friendly state.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from tqdm import tqdm

from stack_common import (
    DEFAULT_STACK_CONFIG_REL,
    infer_stack_root,
    read_toml,
    resolve_path,
    resolve_stack_config,
)


def load_state(path: Path) -> dict:
    """Load run execution state from JSON.

    Args:
        path: Path to run state file.

    Returns:
        State dictionary. Returns an empty default state if file is missing.
    """
    if not path.exists():
        return {"runs": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def save_state(path: Path, state: dict) -> None:
    """Persist run execution state to JSON.

    Args:
        path: Path to state file.
        state: State dictionary to write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    state["updated_utc"] = datetime.now(timezone.utc).isoformat()
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
    os.replace(tmp_path, path)


def runfile_sha256(path: Path) -> str:
    """Compute SHA-256 fingerprint of a runfile for resume safety.

    Args:
        path: Runfile path.

    Returns:
        Hex SHA-256 digest string.
    """
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def run_one(runfile: Path, logfile: Path, disable_hdf5_file_locking: bool) -> int:
    """Execute one COMPASS run file and append output to a log.

    Why:
        This step performs the real COMPASS processing work for one run file.

    Args:
        runfile: Shell script generated by COMPASS.
        logfile: Destination log file path.
        disable_hdf5_file_locking: If True, set `HDF5_USE_FILE_LOCKING=FALSE`
            for compatibility with filesystems where HDF5 locking is unstable.

    Returns:
        Process return code.
    """
    logfile.parent.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    if disable_hdf5_file_locking:
        env["HDF5_USE_FILE_LOCKING"] = "FALSE"
    with logfile.open("a", encoding="utf-8") as log:
        start = datetime.now(timezone.utc).isoformat()
        log.write(f"\n[{start}] START {runfile}\n")
        proc = subprocess.run(
            ["bash", str(runfile)],
            stdout=log,
            stderr=subprocess.STDOUT,
            env=env,
            check=False,
        )
        end = datetime.now(timezone.utc).isoformat()
        log.write(f"[{end}] END rc={proc.returncode}\n")
        return proc.returncode


def main() -> int:
    """Parse CLI args and execute pending COMPASS run files.

    Why:
        Run the prepared coregistration/preprocessing tasks in a resumable way.

    Technical details:
        - Resolves work/log directories from config with CLI overrides.
        - Skips completed runfiles unless `--no-resume` is used.
        - Writes per-run status, timestamps, return codes, and log paths.
        - Supports capped trial runs and optional continue-on-error mode.

    Returns:
        Exit code (0 for success).
    """
    parser = argparse.ArgumentParser(
        description="Execute COMPASS run files generated by 07_prepare_compass_stack.py."
    )
    parser.add_argument(
        "--config",
        default=DEFAULT_STACK_CONFIG_REL,
        help="Path to stack TOML config.",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root directory (default: current directory).",
    )
    parser.add_argument(
        "--work-dir",
        default="",
        help="COMPASS work dir override (defaults to processing.compass.work_dir).",
    )
    parser.add_argument(
        "--logs-dir",
        default="",
        help="Logs directory override (default: stack logs/compass).",
    )
    parser.add_argument(
        "--max-runfiles",
        type=int,
        default=0,
        help="Optional cap on number of pending run files (0 = all).",
    )
    parser.add_argument(
        "--no-resume",
        action="store_true",
        help="Re-run run files even if marked completed in state file.",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue processing remaining run files after a failure.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only show what would be run.",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    try:
        config_path = resolve_stack_config(repo_root, args.config)
    except (FileNotFoundError, RuntimeError) as exc:
        print(str(exc), file=sys.stderr)
        return 2
    cfg = read_toml(config_path)
    stack_root = infer_stack_root(config_path)
    compass_cfg = cfg.get("processing", {}).get("compass", {})
    browse_image_enabled = bool(compass_cfg.get("browse_image", False))
    disable_hdf5_file_locking = bool(compass_cfg.get("disable_hdf5_file_locking", True))

    work_dir_value = args.work_dir or compass_cfg.get(
        "work_dir",
        str(stack_root / "stack" / "compass"),
    )
    work_dir = resolve_path(repo_root, work_dir_value)
    run_dir = work_dir / "run_files"
    if not run_dir.exists():
        print(f"Missing run_files directory: {run_dir}", file=sys.stderr)
        print("Run 07_prepare_compass_stack.py first.", file=sys.stderr)
        return 2

    logs_default = str(stack_root / "logs" / "compass")
    logs_dir = resolve_path(repo_root, args.logs_dir or compass_cfg.get("logs_dir", logs_default))
    state_path = work_dir / "run_state.json"

    runfiles = sorted(run_dir.glob("run_*.sh"))
    if not runfiles:
        print(f"No run files found under {run_dir}", file=sys.stderr)
        return 2

    state = load_state(state_path)
    state_runs: dict = state.setdefault("runs", {})
    resume = not args.no_resume
    pending: list[tuple[Path, str]] = []
    skipped_completed = 0
    rerun_due_to_changed_runfile = 0
    for rf in runfiles:
        rf_hash = runfile_sha256(rf)
        prev = state_runs.get(rf.name, {})
        if (
            resume
            and prev.get("status") == "completed"
            and prev.get("runfile_sha256") == rf_hash
        ):
            skipped_completed += 1
            continue
        if resume and prev.get("status") == "completed":
            rerun_due_to_changed_runfile += 1
        pending.append((rf, rf_hash))

    if args.max_runfiles > 0:
        pending = pending[: args.max_runfiles]

    print(f"Config: {config_path}")
    print(f"Work dir: {work_dir}")
    print(f"Run files total: {len(runfiles)}")
    print(f"Resume mode: {resume}")
    print(f"Already completed (skipped): {skipped_completed}")
    print(f"Completed but changed runfile (will rerun): {rerun_due_to_changed_runfile}")
    print(f"Pending to run now: {len(pending)}")
    print(f"Logs dir: {logs_dir}")
    print(f"State file: {state_path}")
    print(f"Runconfig browse image enabled: {browse_image_enabled}")
    print(f"HDF5 file locking disabled: {disable_hdf5_file_locking}")

    if args.dry_run:
        return 0

    if not pending:
        print("Nothing to run.")
        return 0

    failures = 0
    with tqdm(total=len(pending), desc="COMPASS runfiles", unit="run", dynamic_ncols=True) as bar:
        for rf, rf_hash in pending:
            tqdm.write(f"Running: {rf.name}")
            started = datetime.now(timezone.utc).isoformat()
            log_path = logs_dir / f"{rf.stem}.log"
            rc = run_one(
                rf,
                log_path,
                disable_hdf5_file_locking=disable_hdf5_file_locking,
            )
            finished = datetime.now(timezone.utc).isoformat()

            state_runs[rf.name] = {
                "status": "completed" if rc == 0 else "failed",
                "returncode": rc,
                "log_file": str(log_path),
                "started_utc": started,
                "finished_utc": finished,
                "runfile_sha256": rf_hash,
            }
            save_state(state_path, state)
            bar.update(1)

            if rc != 0:
                failures += 1
                tqdm.write(f"FAILED: {rf.name} (rc={rc}) -> {log_path}")
                if not args.continue_on_error:
                    break

    print(f"Failures in this run: {failures}")
    print(f"State updated: {state_path}")
    if failures > 0:
        return 4
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
